# Generated by Django 5.2.9 on 2025-12-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Mã đơn hàng')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('processing', 'Đang xử lý'), ('shipping', 'Đang giao hàng'), ('delivered', 'Đã giao hàng'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='Tên người nhận')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('city', models.CharField(max_length=100, verbose_name='Thành phố')),
                ('district', models.CharField(max_length=100, verbose_name='Quận/Huyện')),
                ('ward', models.CharField(blank=True, max_length=100, verbose_name='Phường/Xã')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('payment_method', models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng'), ('bank_transfer', 'Chuyển khoản ngân hàng'), ('momo', 'Ví MoMo'), ('vnpay', 'VNPay')], default='cod', max_length=20, verbose_name='Phương thức thanh toán')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('paid', 'Đã thanh toán'), ('refunded', 'Đã hoàn tiền')], default='unpaid', max_length=20, verbose_name='Trạng thái thanh toán')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tạm tính')),
                ('shipping_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Phí vận chuyển')),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giảm giá')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng cộng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('product_image', models.URLField(blank=True, verbose_name='Hình ảnh')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Đơn giá')),
            ],
            options={
                'verbose_name': 'Sản phẩm trong đơn',
                'verbose_name_plural': 'Sản phẩm trong đơn',
            },
        ),
    ]
