# Generated by Django 5.2.9 on 2025-12-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='to_district_id',
            field=models.IntegerField(blank=True, help_text='GHN district ID for shipping', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='to_ward_code',
            field=models.CharField(blank=True, help_text='GHN ward code for shipping', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, help_text='GHN order code / tracking number', max_length=50),
        ),
    ]
