# Generated by Django 5.2.9 on 2025-12-26 01:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('vnpay', 'VNPay'), ('momo', 'MoMo'), ('cod', 'COD')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('currency', models.CharField(default='VND', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại'), ('cancelled', 'Đã hủy'), ('refunded', 'Đã hoàn tiền')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('payment_url', models.TextField(blank=True, null=True)),
                ('provider_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('processing', 'Đang xử lý'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại')], default='pending', max_length=20)),
                ('refund_id', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hoàn tiền',
                'verbose_name_plural': 'Hoàn tiền',
                'ordering': ['-created_at'],
            },
        ),
    ]
