# Generated by Django 5.2.9 on 2025-12-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_user_deleted_at_user_email_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='district_id',
            field=models.IntegerField(blank=True, help_text='GHN District ID', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='province_id',
            field=models.IntegerField(blank=True, help_text='GHN Province ID', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ward_code',
            field=models.CharField(blank=True, help_text='GHN Ward Code', max_length=20),
        ),
    ]
