# Generated by Django 5.2.9 on 2025-12-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_add_ghn_address_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(blank=True, choices=[('totp', 'Authenticator App'), ('email', 'Email OTP')], default='totp', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_secret',
            field=models.CharField(blank=True, help_text='Secret key for TOTP 2FA', max_length=32, null=True),
        ),
    ]
