# Generated by Django 5.2.9 on 2025-12-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_user_two_factor_method_user_two_factor_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list, help_text='List of one-time backup codes'),
        ),
    ]
