# Generated by Django 5.2.9 on 2025-12-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='OWLS', max_length=255)),
                ('site_description', models.TextField(blank=True, default='Future Tech Store')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('contact_email', models.EmailField(default='support@owls.com', max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('enable_cod', models.BooleanField(default=True)),
                ('enable_stripe', models.BooleanField(default=False)),
                ('shipping_fee_flat', models.DecimalField(decimal_places=2, default=50000, max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=1000000, max_digits=12)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
